/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555834 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555185 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555182 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
NTI33555185.base = NTI33555182;
NTI33555186.base = NTI33555182;
var NNI33555182 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555185, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555186, name: "up", sons: null}]};
NTI33555182.node = NNI33555182;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555182.base = NTI33555178;
NTI33555183.base = NTI33555182;
NTI134217745.base = NTI33555183;
var NNI33555834 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555834.node = NNI33555834;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555183;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555183;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555183;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557215, src_33557216, ti_33557217) {
  var result_33557226 = null;

    switch (ti_33557217.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557206(ti_33557217))) {
      result_33557226 = src_33557216;
      }
      else {
        result_33557226 = [src_33557216[0], src_33557216[1]];
      }
      
      break;
    case 19:
            if (dest_33557215 === null || dest_33557215 === undefined) {
        dest_33557215 = {};
      }
      else {
        for (var key in dest_33557215) { delete dest_33557215[key]; }
      }
      for (var key in src_33557216) { dest_33557215[key] = src_33557216[key]; }
      result_33557226 = dest_33557215;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557217.base == null))) {
      result_33557226 = nimCopy(dest_33557215, src_33557216, ti_33557217.base);
      }
      else {
      if ((ti_33557217.kind == 17)) {
      result_33557226 = (dest_33557215 === null || dest_33557215 === undefined) ? {m_type: ti_33557217} : dest_33557215;
      }
      else {
        result_33557226 = (dest_33557215 === null || dest_33557215 === undefined) ? {} : dest_33557215;
      }
      }
      nimCopyAux(result_33557226, src_33557216, ti_33557217.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557216)) { 
        if(dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
          dest_33557215 = new src_33557216.constructor(src_33557216);
        } else {
          dest_33557215.set(src_33557216, 0);
        }
        result_33557226 = dest_33557215;
      } else {
        if (src_33557216 === null) {
          result_33557226 = null;
        }
        else {
          if (dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
            dest_33557215 = new Array(src_33557216.length);
          }
          result_33557226 = dest_33557215;
          for (var i = 0; i < src_33557216.length; ++i) {
            result_33557226[i] = nimCopy(result_33557226[i], src_33557216[i], ti_33557217.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557216 === null) {
        result_33557226 = null;
      }
      else {
        if (dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
          dest_33557215 = new Array(src_33557216.length);
        }
        result_33557226 = dest_33557215;
        for (var i = 0; i < src_33557216.length; ++i) {
          result_33557226[i] = nimCopy(result_33557226[i], src_33557216[i], ti_33557217.base);
        }
      }
    
      break;
    case 28:
            if (src_33557216 !== null) {
        result_33557226 = src_33557216.slice(0);
      }
    
      break;
    default: 
      result_33557226 = src_33557216;
      break;
    }

  return result_33557226;

}

function arrayConstr(len_33557258, value_33557259, typ_33557260) {
        var result = new Array(len_33557258);
    for (var i = 0; i < len_33557258; ++i) result[i] = nimCopy(null, value_33557259, typ_33557260);
    return result;
  

  
}

function mnewString(len_33556956) {
        return new Array(len_33556956);
  

  
}

function addInt(a_33557003, b_33557004) {
        var result = a_33557003 + b_33557004;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557268, a_33557269, b_33557270) {
  var result_33557271 = 0;

  BeforeRet: {
    if (((a_33557269 <= i_33557268) && (i_33557268 <= b_33557270))) {
    result_33557271 = i_33557268;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557271;

}

function chckIndx(i_33557263, a_33557264, b_33557265) {
  var result_33557266 = 0;

  BeforeRet: {
    if (((a_33557264 <= i_33557263) && (i_33557263 <= b_33557265))) {
    result_33557266 = i_33557263;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557263, a_33557264, b_33557265);
    }
    
  };

  return result_33557266;

}

function cstrToNimstr(c_33556857) {
      var ln = c_33556857.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556857.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556857.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556860) {
  var result_33556861 = null;

    var res_33556899 = newSeq_33556878((s_33556860).length);
    var i_33556900 = 0;
    var j_33556901 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556900 < (s_33556860).length)) break Label2;
          var c_33556902 = s_33556860[i_33556900];
          if ((c_33556902 < 128)) {
          res_33556899[j_33556901] = String.fromCharCode(c_33556902);
          i_33556900 += 1;
          }
          else {
            var helper_33556915 = newSeq_33556878(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556916 = c_33556902.toString(16);
                  if ((((code_33556916) == null ? 0 : (code_33556916).length) == 1)) {
                  helper_33556915.push("%0");;
                  }
                  else {
                  helper_33556915.push("%");;
                  }
                  
                  helper_33556915.push(code_33556916);;
                  i_33556900 += 1;
                  if ((((s_33556860).length <= i_33556900) || (s_33556860[i_33556900] < 128))) {
                  break Label3;
                  }
                  
                  c_33556902 = s_33556860[i_33556900];
                }
            };
++excHandler;
            try {
            res_33556899[j_33556901] = decodeURIComponent(helper_33556915.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556899[j_33556901] = helper_33556915.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556901 += 1;
        }
    };
    if (res_33556899.length < j_33556901) { for (var i = res_33556899.length ; i < j_33556901 ; ++i) res_33556899.push(null); }
               else { res_33556899.length = j_33556901; };
    result_33556861 = res_33556899.join("");

  return result_33556861;

}

function raiseException(e_33556648, ename_33556649) {
    e_33556648.name = ename_33556649;
    if ((excHandler == 0)) {
    unhandledException(e_33556648);
    }
    
    e_33556648.trace = nimCopy(null, rawWriteStackTrace_33556605(), NTI33554449);
    throw e_33556648;

  
}

function makeNimstrLit(c_33556854) {
      var result = [];
  for (var i = 0; i < c_33556854.length; ++i) {
    result[i] = c_33556854.charCodeAt(i);
  }
  return result;
  

  
}

function eqStrings(a_33556994, b_33556995) {
        if (a_33556994 == b_33556995) return true;
    if (a_33556994 === null && b_33556995.length == 0) return true;
    if (b_33556995 === null && a_33556994.length == 0) return true;
    if ((!a_33556994) || (!b_33556995)) return false;
    var alen = a_33556994.length;
    if (alen != b_33556995.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_33556994[i] != b_33556995[i]) return false;
    return true;
  

  
}

function subInt(a_33557007, b_33557008) {
        var result = a_33557007 - b_33557008;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557206(ti_33557207) {
  var result_33557208 = false;

  BeforeRet: {
    result_33557208 = !((ConstSet1[ti_33557207.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557208;

}

function nimCopyAux(dest_33557219, src_33557220, n_33557221) {
    switch (n_33557221.kind) {
    case 0:
      break;
    case 1:
            dest_33557219[n_33557221.offset] = nimCopy(dest_33557219[n_33557221.offset], src_33557220[n_33557221.offset], n_33557221.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557221.sons.length; i++) {
      nimCopyAux(dest_33557219, src_33557220, n_33557221.sons[i]);
    }
    
      break;
    case 3:
            dest_33557219[n_33557221.offset] = nimCopy(dest_33557219[n_33557221.offset], src_33557220[n_33557221.offset], n_33557221.typ);
      for (var i = 0; i < n_33557221.sons.length; ++i) {
        nimCopyAux(dest_33557219, src_33557220, n_33557221.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556392(x_33556393, x_33556393_Idx, y_33556394) {
          if (x_33556393[x_33556393_Idx] === null) { x_33556393[x_33556393_Idx] = []; }
      var off = x_33556393[x_33556393_Idx].length;
      x_33556393[x_33556393_Idx].length += y_33556394.length;
      for (var i = 0; i < y_33556394.length; ++i) {
        x_33556393[x_33556393_Idx][off+i] = y_33556394.charCodeAt(i);
      }
    

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557001) {
        if (a_33557001 > 2147483647 || a_33557001 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556783, a_33556784, b_33556785) {
    var Temporary1;

    if ((b_33556785 < a_33556784)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556783) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556784) || [],[32,46,46,32] || [],HEX24_369098760(b_33556785) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_301990072(result_301990074, result_301990074_Idx, x_301990075, start_301990076, n_301990077) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_301990078 = (result_301990074[result_301990074_Idx]).length;
    F.line = 44;
    if (result_301990074[result_301990074_Idx].length < (Temporary1 = chckRange(addInt(old_301990078, n_301990077), 0, 2147483647), Temporary1)) { for (var i = result_301990074[result_301990074_Idx].length; i < Temporary1; ++i) result_301990074[result_301990074_Idx].push(0); }
         else {result_301990074[result_301990074_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990092 = 0;
      F.line = 119;
      var i_654311494 = 0;
      Label3: {
        F.line = 120;
          Label4: while (true) {
          if (!(i_654311494 < n_301990077)) break Label4;
            F.line = 49;
            iHEX60gensym4_301990092 = i_654311494;
            F.line = 49;
            result_301990074[result_301990074_Idx][chckIndx(addInt(old_301990078, iHEX60gensym4_301990092), 0, (result_301990074[result_301990074_Idx]).length - 1)] = x_301990075.charCodeAt(chckIndx(addInt(start_301990076, iHEX60gensym4_301990092), 0, (x_301990075).length - 1));
            F.line = 122;
            i_654311494 = addInt(i_654311494, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990068(result_301990070, result_301990070_Idx, x_301990071) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_301990072(result_301990070, result_301990070_Idx, x_301990071, 0, ((x_301990071) == null ? 0 : (x_301990071).length));
  framePtr = F.prev;

  
}

function addInt_301990093(result_301990094, result_301990094_Idx, x_301990095) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    addChars_301990068(result_301990094, result_301990094_Idx, ((x_301990095) + ""));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    addInt_301990093(result_301990112, result_301990112_Idx, BigInt(x_301990113));
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_301990111(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}

function auxWriteStackTrace_33556518(f_33556519) {
  var result_33556520 = [[]];

    var it_33556528 = f_33556519;
    var i_33556529 = 0;
    var total_33556530 = 0;
    var tempFrames_33556531 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555834);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556528 == null)) && (i_33556529 <= 63))) break Label2;
          tempFrames_33556531[i_33556529].Field0 = it_33556528.procname;
          tempFrames_33556531[i_33556529].Field1 = it_33556528.line;
          tempFrames_33556531[i_33556529].Field2 = it_33556528.filename;
          i_33556529 += 1;
          total_33556530 += 1;
          it_33556528 = it_33556528.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556528 == null))) break Label4;
          total_33556530 += 1;
          it_33556528 = it_33556528.prev;
        }
    };
    result_33556520[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556530 == i_33556529))) {
    result_33556520[0].push.apply(result_33556520[0], [40]);;
    result_33556520[0].push.apply(result_33556520[0], HEX24_369098760((total_33556530 - i_33556529)));;
    result_33556520[0].push.apply(result_33556520[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556564 = 0;
      var colontmp__654311486 = 0;
      colontmp__654311486 = (i_33556529 - 1);
      var res_654311488 = colontmp__654311486;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_654311488)) break Label7;
            j_33556564 = res_654311488;
            result_33556520[0].push.apply(result_33556520[0], cstrToNimstr(tempFrames_33556531[j_33556564].Field2));;
            if ((0 < tempFrames_33556531[j_33556564].Field1)) {
            result_33556520[0].push.apply(result_33556520[0], [40]);;
            addInt_301990111(result_33556520, 0, tempFrames_33556531[j_33556564].Field1);
            if (false) {
            result_33556520[0].push.apply(result_33556520[0], [44,32]);;
            addInt_301990111(result_33556520, 0, 0);
            }
            
            result_33556520[0].push.apply(result_33556520[0], [41]);;
            }
            
            result_33556520[0].push.apply(result_33556520[0], [32,97,116,32]);;
            add_33556392(result_33556520, 0, tempFrames_33556531[j_33556564].Field0);
            result_33556520[0].push.apply(result_33556520[0], [10]);;
            res_654311488 -= 1;
          }
      };
    };

  return result_33556520[0];

}

function rawWriteStackTrace_33556605() {
  var result_33556606 = [];

    if (!((framePtr == null))) {
    result_33556606 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556518(framePtr) || []), NTI33554449);
    }
    else {
      result_33556606 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556606;

}

function newSeq_33556878(len_33556880) {
  var result_33556881 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 603;
    result_33556881 = new Array(len_33556880); for (var i = 0 ; i < len_33556880 ; ++i) { result_33556881[i] = null; }  framePtr = F.prev;

  return result_33556881;

}

function unhandledException(e_33556644) {
    var buf_33556645 = [[]];
    if (!(((e_33556644.message).length == 0))) {
    buf_33556645[0].push.apply(buf_33556645[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556645[0].push.apply(buf_33556645[0], e_33556644.message);;
    }
    else {
    buf_33556645[0].push.apply(buf_33556645[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556645[0].push.apply(buf_33556645[0], [32,91]);;
    add_33556392(buf_33556645, 0, e_33556644.name);
    buf_33556645[0].push.apply(buf_33556645[0], [93,10]);;
    buf_33556645[0].push.apply(buf_33556645[0], rawWriteStackTrace_33556605());;
    var cbuf_33556646 = toJSStr(buf_33556645[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556646);
  }
  else {
    throw cbuf_33556646;
  }
  

  
}

function sysFatal_268435498(message_268435501) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    raiseException({message: nimCopy(null, message_268435501, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435496(msg_268435497) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    sysFatal_268435498(msg_268435497);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435532(msg_268435533) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    raiseAssert_268435496(msg_268435533);
  framePtr = F.prev;

  
}
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
if (!((BigInt(1234567890) == BigInt("1234567890")))) {
F.line = 14;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(9, 3) `big(1234567890) == big\"1234567890\"` "));
}

if (!(((BigInt(999) == BigInt(999)) && (BigInt(999) == BigInt(999))))) {
F.line = 14;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(10, 3) `0b00000000000000000000001111100111.big == 0o000000001747.big and\x0A    0o000000001747.big == 999.big` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
if (!((BigInt("-1") == (BigInt("1") - BigInt("2"))))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(9, 3) `-1\'big == 1\'big - 2\'big` "));
}

if (!((BigInt("-12") == BigInt("-12")))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(11, 3) `-12\'big == big\"-12\"` "));
}

if (!((BigInt("12") == BigInt(12)))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(12, 3) `12\'big == 12.big` "));
}

if (!((BigInt("0b101") == BigInt(5)))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(13, 3) `0b101\'big == 0b00000000000000000000000000000101.big` "));
}

if (!((BigInt("0o701") == BigInt(449)))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(14, 3) `0o701\'big == 0o000000000701.big` "));
}

if (!((BigInt("0xdeadbeaf") == BigInt(3735928495n)))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(15, 3) `0xdeadbeaf\'big == 0x00000000DEADBEAF\'i64.big` "));
}

if (!((BigInt("0xffffffffffffffff") == ((BigInt("1") << BigInt("64")) - BigInt("1"))))) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(16, 3) `0xffffffffffffffff\'big == (1\'big shl 64\'big) - 1\'big` "));
}

if (false) {
F.line = 21;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(17, 3) `not compiles(static(12\'big))` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
if (!((BigInt("2147483647").toString(2) == "1111111111111111111111111111111"))) {
F.line = 41;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim(9, 3) `big\"2147483647\".toCstring(2) == \"1111111111111111111111111111111\".cstring` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX24_671088669(this_671088670) {
  var result_671088671 = [];

  var F = {procname: "jsbigints.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
  framePtr = F;
    F.line = 49;
    result_671088671 = nimCopy(null, (cstrToNimstr(this_671088670.toString()) || []).concat([110]), NTI33554449);
  framePtr = F.prev;

  return result_671088671;

}
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
if (!(eqStrings(HEX24_671088669(BigInt("1024")), [49,48,50,52,110]))) {
F.line = 50;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim(9, 3) `$big\"1024\" == \"1024n\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 13; return BigInt.asIntN(b, i) })() == BigInt("3")))) {
F.line = 57;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim(9, 3) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToInt(13) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 66; return BigInt.asUintN(b, i) })() == BigInt("3")))) {
F.line = 64;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim(9, 3) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToUint(66) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
if (!((Number(BigInt("2147483647")) == 2147483647))) {
F.line = 69;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim(9, 3) `toNumber(big\"2147483647\") == 2147483647.int` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") + BigInt("1")) == BigInt("10")))) {
F.line = 73;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim(9, 3) `(big\"9\" + big\"1\") == big\"10\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") - BigInt("1")) == BigInt("8")))) {
F.line = 77;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim(9, 3) `(big\"9\" - big\"1\") == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
if (!(((BigInt("42") * BigInt("9")) == BigInt("378")))) {
F.line = 81;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim(9, 3) `(big\"42\" * big\"9\") == big\"378\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") / BigInt("3")) == BigInt("4")))) {
F.line = 86;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(9, 3) `big\"13\" div big\"3\" == big\"4\"` "));
}

if (!(((BigInt("-13") / BigInt("3")) == BigInt("-4")))) {
F.line = 86;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(10, 3) `big\"-13\" div big\"3\" == big\"-4\"` "));
}

if (!(((BigInt("13") / BigInt("-3")) == BigInt("-4")))) {
F.line = 86;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(11, 3) `big\"13\" div big\"-3\" == big\"-4\"` "));
}

if (!(((BigInt("-13") / BigInt("-3")) == BigInt("4")))) {
F.line = 86;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(12, 3) `big\"-13\" div big\"-3\" == big\"4\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") % BigInt("3")) == BigInt("1")))) {
F.line = 94;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(9, 3) `big\"13\" mod big\"3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("3")) == BigInt("-1")))) {
F.line = 94;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(10, 3) `big\"-13\" mod big\"3\" == big\"-1\"` "));
}

if (!(((BigInt("13") % BigInt("-3")) == BigInt("1")))) {
F.line = 94;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(11, 3) `big\"13\" mod big\"-3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("-3")) == BigInt("-1")))) {
F.line = 94;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(12, 3) `big\"-13\" mod big\"-3\" == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
if (!((BigInt("2") < BigInt("9")))) {
F.line = 101;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim(9, 3) `big\"2\" < big\"9\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
if (!((BigInt("1") <= BigInt("5")))) {
F.line = 105;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim(9, 3) `big\"1\" <= big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
if (!((BigInt("42") == BigInt("42")))) {
F.line = 109;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim(9, 3) `big\"42\" == big\"42\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
if (!((((BigInt("2")) ** BigInt("64")) == BigInt("18446744073709551616")))) {
F.line = 114;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(9, 3) `big\"2\" ** big\"64\" == big\"18446744073709551616\"` "));
}

if (!((((BigInt("-2")) ** BigInt("3")) == BigInt("-8")))) {
F.line = 114;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(10, 3) `big\"-2\" ** big\"3\" == big\"-8\"` "));
}

if (!(((((-BigInt("2"))) ** BigInt("2")) == BigInt("4")))) {
F.line = 114;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(11, 3) `-big\"2\" ** big\"2\" == big\"4\"` "));
}

if (!((((BigInt("0")) ** BigInt("0")) == BigInt("1")))) {
F.line = 114;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(12, 3) `big\"0\" ** big\"0\" == big\"1\"` "));
}

F.line = 114;
var ok_922746903 = [false];
F.line = 114;
++excHandler;
try {
F.line = 114;
var _ = ((BigInt("2")) ** BigInt("-1"));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
framePtr = F;
F.line = 114;
ok_922746903[0] = true;
lastJSError = prevJSError;
} finally {
framePtr = F;
}
if (!(ok_922746903[0])) {
F.line = 114;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(16, 3) `ok` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") & BigInt("2")) == BigInt("2")))) {
F.line = 125;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim(9, 3) `(big\"555\" and big\"2\") == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") | BigInt("2")) == BigInt("555")))) {
F.line = 129;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim(9, 3) `(big\"555\" or big\"2\") == big\"555\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") ^ BigInt("2")) == BigInt("553")))) {
F.line = 133;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim(9, 3) `(big\"555\" xor big\"2\") == big\"553\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") << BigInt("2")) == BigInt("3996")))) {
F.line = 137;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim(9, 3) `(big\"999\" shl big\"2\") == big\"3996\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") >> BigInt("2")) == BigInt("249")))) {
F.line = 141;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim(9, 3) `(big\"999\" shr big\"2\") == big\"249\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
if (!(((-BigInt("10101010101")) == BigInt("-10101010101")))) {
F.line = 145;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim(9, 3) `-(big\"10101010101\") == big\"-10101010101\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
F.line = 149;
var big1_1040187395 = [BigInt("1")];
F.line = 149;
(++[big1_1040187395, 0][0][0]);
if (!((big1_1040187395[0] == BigInt("2")))) {
F.line = 149;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim(11, 3) `big1 == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
F.line = 155;
var big1_1056964611 = [BigInt("2")];
F.line = 155;
(--[big1_1056964611, 0][0][0]);
if (!((big1_1056964611[0] == BigInt("1")))) {
F.line = 155;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim(11, 3) `big1 == big\"1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
F.line = 161;
var big1_1073741827 = [BigInt("1")];
F.line = 161;
([big1_1073741827, 0][0][0] += BigInt("2"));
if (!((big1_1073741827[0] == BigInt("3")))) {
F.line = 161;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim(11, 3) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
F.line = 167;
var big1_1090519043 = [BigInt("1")];
F.line = 167;
([big1_1090519043, 0][0][0] -= BigInt("2"));
if (!((big1_1090519043[0] == BigInt("-1")))) {
F.line = 167;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim(11, 3) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
F.line = 173;
var big1_1107296259 = [BigInt("1")];
F.line = 173;
([big1_1107296259, 0][0][0] += BigInt("2"));
if (!((big1_1107296259[0] == BigInt("3")))) {
F.line = 173;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim(11, 3) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
F.line = 179;
var big1_1124073475 = [BigInt("1")];
F.line = 179;
([big1_1124073475, 0][0][0] -= BigInt("2"));
if (!((big1_1124073475[0] == BigInt("-1")))) {
F.line = 179;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim(11, 3) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
F.line = 185;
var big1_1140850691 = [BigInt("2")];
F.line = 185;
([big1_1140850691, 0][0][0] *= BigInt("4"));
if (!((big1_1140850691[0] == BigInt("8")))) {
F.line = 185;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim(11, 3) `big1 == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
F.line = 192;
var big1_1157627907 = [BigInt("11")];
F.line = 192;
([big1_1157627907, 0][0][0] /= BigInt("2"));
if (!((big1_1157627907[0] == BigInt("5")))) {
F.line = 192;
failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim(11, 3) `big1 == big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX3DHEX3D_1174405180(x_1174405182, y_1174405183) {
  var result_1174405184 = false;

  var F = {procname: "==.==", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/comparisons.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 326;
    var sameObject_1174405192 = false;
    F.line = 327;
    sameObject_1174405192 = x_1174405182 === y_1174405183
    if (sameObject_1174405192) {
    F.line = 328;
    result_1174405184 = true;
    break BeforeRet;
    }
    
    if (!(((x_1174405182).length == (y_1174405183).length))) {
    F.line = 331;
    result_1174405184 = false;
    break BeforeRet;
    }
    
    Label1: {
      F.line = 333;
      var i_1174405206 = 0;
      F.line = 75;
      var colontmp__1174405296 = 0;
      F.line = 333;
      colontmp__1174405296 = subInt((x_1174405182).length, 1);
      F.line = 90;
      var res_1174405298 = 0;
      Label2: {
        F.line = 91;
          Label3: while (true) {
          if (!(res_1174405298 <= colontmp__1174405296)) break Label3;
            F.line = 333;
            i_1174405206 = res_1174405298;
            if (!((x_1174405182[chckIndx(i_1174405206, 0, (x_1174405182).length - 1)] == y_1174405183[chckIndx(i_1174405206, 0, (y_1174405183).length - 1)]))) {
            F.line = 335;
            result_1174405184 = false;
            break BeforeRet;
            }
            
            F.line = 93;
            res_1174405298 = addInt(res_1174405298, 1);
          }
      };
    };
    F.line = 337;
    result_1174405184 = true;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_1174405184;

}

function HEX5BHEX5D_1174405212(s_1174405214, i_1174405215) {
  var result_1174405216 = null;
  var result_1174405216_Idx = 0;

  var F = {procname: "[].[]", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/indices.nim", line: 0};
  framePtr = F;
    F.line = 30;
    result_1174405216 = s_1174405214; result_1174405216_Idx = chckIndx(subInt((s_1174405214).length, i_1174405215), 0, (s_1174405214).length - 1);
  framePtr = F.prev;

  return [result_1174405216, result_1174405216_Idx];

}
    var Temporary4;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
Label2: {
  F.line = 208;
  var big1_1174405123 = BigInt("2147483647");
  F.line = 208;
  var big2_1174405124 = BigInt("666");
  if (false) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(12, 5) `JsBigInt isnot int` "));
  }
  
  if (!(!((big1_1174405123 == big2_1174405124)))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(13, 5) `big1 != big2` "));
  }
  
  if (!((big2_1174405124 < big1_1174405123))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(14, 5) `big1 > big2` "));
  }
  
  if (!((big2_1174405124 <= big1_1174405123))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(15, 5) `big1 >= big2` "));
  }
  
  if (!((big2_1174405124 < big1_1174405123))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(16, 5) `big2 < big1` "));
  }
  
  if (!((big2_1174405124 <= big1_1174405123))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(17, 5) `big2 <= big1` "));
  }
  
  if (!(!((big1_1174405123 == big2_1174405124)))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(18, 5) `not (big1 == big2)` "));
  }
  
  F.line = 208;
  var z_1174405165 = 0n;
  if (!(eqStrings(HEX24_671088669(z_1174405165), [48,110]))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(20, 5) `$z == \"0n\"` "));
  }
  
};
Label3: {
  F.line = 208;
  var a_1174405171 = [[]];
  F.line = 208;
  if (a_1174405171[0].length < 2) { for (var i = a_1174405171[0].length ; i < 2 ; ++i) a_1174405171[0].push(0n); }
               else { a_1174405171[0].length = 2; };
  if (!(HEX3DHEX3D_1174405180(a_1174405171[0], [BigInt("0"), BigInt("0")]))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(24, 5) `a == @[big\"0\", big\"0\"]` "));
  }
  
  if (!(((Temporary4 = HEX5BHEX5D_1174405212(a_1174405171[0], 1), Temporary4)[0][Temporary4[1]] == BigInt("0")))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(25, 5) `a[^1] == big\"0\"` "));
  }
  
  F.line = 208;
  var b_1174405239 = [0n];
  if (!((b_1174405239[0] == BigInt("0")))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(27, 5) `b == big\"0\"` "));
  }
  
  if (!((b_1174405239[0] == 0n))) {
  F.line = 208;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(28, 5) `b == JsBigInt.default` "));
  }
  
};
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
